#!/command/with-contenv bash
# shellcheck shell=bash
#
# Islandora Lite first-start install. Mirrors the upstream
# drupal/rootfs/etc/s6-overlay/scripts/install.sh (same structure, same markers) with
# the Lite body from isle-dc's custom.Makefile (lite_dev / lite-finalize / lite_hydrate).
# Lite has no Fedora and no ActiveMQ, so neither is waited for.
set -e

# shellcheck disable=SC1091
source /etc/islandora/utilities.sh

readonly SITE="default"

function configure {
    # Work around for when the cache is in a bad state, as Drush will access
    # the cache before rebuilding it for some dumb reason, preventing
    # Drush from being able to clear it.
    local params
    params=$(/var/www/drupal/web/core/scripts/rebuild_token_calculator.sh 2>/dev/null)
    curl -L "${DRUSH_OPTIONS_URI}/core/rebuild.php?${params}"
    drush --root=/var/www/drupal --uri="${DRUSH_OPTIONS_URI}" cache:rebuild

    drush --root=/var/www/drupal --uri="${DRUSH_OPTIONS_URI}" -y user:role:add administrator admin || true
    drush --root=/var/www/drupal --uri="${DRUSH_OPTIONS_URI}" -y pm:uninstall pgsql sqlite || true

    # Services and URLs that depend on this stack (re-runnable: `make lite-hydrate`).
    lite-hydrate.sh

    # Solr core (config generated by search_api_solr, shared with the solr container
    # through the drupal-solr-config volume) and Blazegraph namespace.
    create_solr_core_with_default_config "${SITE}" || echo -e "\n\nERROR: SOLR was not initialized. Check the logs above for more details.\n\n"
    # The search_api_solr config.zip also contains a core.properties, unpacked into
    # <core>/conf/. On the next Solr start core discovery registers it as a phantom
    # core named "conf" (upstream ships the same stray file). Remove it.
    rm -f "/opt/solr/server/solr/${DRUPAL_DEFAULT_SOLR_CORE}/conf/core.properties"
    create_blazegraph_namespace_with_default_properties "${SITE}"

    # The only Islandora migration the Lite site ships. (Drush 13 has no --userid option.)
    drush --root=/var/www/drupal --uri="${DRUSH_OPTIONS_URI}" -y migrate:import islandora_tags || true
    drush --root=/var/www/drupal --uri="${DRUSH_OPTIONS_URI}" cache:rebuild
}

function install {
    # wait for mariadb, solr, blazegraph and fits to be available
    wait_for_service "${SITE}" db
    wait_for_service "${SITE}" solr
    wait_for_service "${SITE}" triplestore
    wait_for_service "${SITE}" fits

    create_database "${SITE}"
    # drush si --existing-config minimal (DRUPAL_DEFAULT_INSTALL_EXISTING_CONFIG=true,
    # DRUPAL_DEFAULT_PROFILE=minimal from docker-compose.yml). Writes settings.php.
    install_site "${SITE}"

    configure
}

function mysql_count_query {
    cat <<-EOF
SELECT COUNT(DISTINCT table_name)
FROM information_schema.columns
WHERE table_schema = '${DRUPAL_DEFAULT_DB_NAME}';
EOF
}

# Check the number of tables to determine if it has already been installed.
function installed {
    local count
    count=$(execute-sql-file.sh <(mysql_count_query) -- -N 2>/dev/null) || exit $?
    [[ $count -ne 0 ]]
}

# Required even if not installing.
function setup() {
    local site drupal_root subdir site_directory public_files_directory private_files_directory twig_cache_directory
    site="${1}"
    shift

    drupal_root=/var/www/drupal/web
    subdir=$(drupal_site_env "${site}" "SUBDIR")
    site_directory="${drupal_root}/sites/${subdir}"
    public_files_directory="${site_directory}/files"
    private_files_directory="/var/www/drupal/private"
    twig_cache_directory="${private_files_directory}/php"

    # Ensure the files directories are writable by nginx, as when it is a new volume it is owned by root.
    mkdir -p "${site_directory}" "${public_files_directory}" "${private_files_directory}" "${twig_cache_directory}"
    chown nginx:nginx "${site_directory}" "${public_files_directory}" "${private_files_directory}" "${twig_cache_directory}"
    chmod ug+rw "${site_directory}" "${public_files_directory}" "${private_files_directory}" "${twig_cache_directory}"

    # Lite keeps private files under the web root (assets/patches/default_settings.txt).
    mkdir -p "${site_directory}/private"
    chown nginx:nginx "${site_directory}/private"
    chmod ug+rw "${site_directory}/private"
}

function drush_cache_setup {
    # Make sure the default drush cache directory exists and is writeable.
    mkdir -p /tmp/drush-/cache
    chmod a+rwx /tmp/drush-/cache
}

# External processes can look for `/installed` to check if installation is completed.
function finished {
    touch /installed
    cat <<-EOT


#####################
# Install Completed #
#####################
EOT
}

function main() {
    cd /var/www/drupal
    drush_cache_setup
    for_all_sites setup

    if installed; then
        echo "Already Installed"
    else
        echo "Installing"
        install
    fi
    finished
}
main
